name: kasabike
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # PACKAGES
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.5
  firebase_messaging: ^11.2.4
  firebase_analytics: ^9.0.4
  firebase_performance: ^0.8.0+3
  firebase_auth: ^3.3.7
  firebase_dynamic_links: ^4.0.3
  social_media_logins:
      git:
        url: https://github.com/responilla07/social_media_logins
        ref: main

  flutter_svg: ^0.21.0
  google_maps_flutter: ^2.2.0
  google_maps_routes: ^1.1.2
  http: ^0.13.4
  flutter_polyline_points: ^1.0.0
  location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/map/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
